-- Generated by: Transformation Agent (Phase 4b) | zone: BRONZE
-- Raw, immutable landing table. All columns typed as STRING (no coercion in Bronze).
-- Partitioned by ingestion_date. External table over the raw S3 prefix.

CREATE EXTERNAL TABLE IF NOT EXISTS advisory_transactions_db.bronze_advisory_transactions (
    transaction_id    STRING,
    account_id        STRING,
    advisor_id        STRING,
    client_id         STRING,
    client_name       STRING,
    client_email      STRING,
    client_ssn        STRING,
    security_id       STRING,
    security_name     STRING,
    asset_class       STRING,
    transaction_type  STRING,
    trade_date        STRING,
    settlement_date   STRING,
    quantity          STRING,
    unit_price        STRING,
    gross_amount      STRING,
    commission        STRING,
    fees              STRING,
    net_amount        STRING,
    currency          STRING,
    account_type      STRING,
    advisor_name      STRING,
    branch_code       STRING
)
PARTITIONED BY (ingestion_date STRING)
STORED AS PARQUET
LOCATION 's3://data-lake-<account>-us-east-1/bronze/advisory_transactions/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');

-- Bronze is append-only. Never UPDATE/DELETE (ADOP `bronze-immutable` invariant).
