-- Generated by: Transformation Agent (Phase 4b) | zone: GOLD
-- Business-ready star schema. Iceberg on S3 Tables, Gold-zone KMS CMK.
-- PII (SSN/email/name) is SUPPRESSED entirely in Gold.

-- ---- Fact ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_fact_transactions (
    transaction_id  STRING,
    account_id      STRING,   -- FK -> gold_dim_account
    advisor_id      STRING,   -- FK -> gold_dim_advisor
    security_id     STRING,   -- FK -> gold_dim_security
    trade_date      DATE,     -- FK -> gold_dim_date
    quantity        DECIMAL(18,2),
    unit_price      DECIMAL(18,2),
    gross_amount    DECIMAL(18,2),
    commission      DECIMAL(18,2),
    fees            DECIMAL(18,2),
    net_amount      DECIMAL(18,2)
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/fact_transactions/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

-- ---- Dimensions ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_dim_account (
    account_id    STRING,
    account_type  STRING,
    branch_code   STRING,
    client_id     STRING   -- pseudonymised only; no direct PII
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/dim_account/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_dim_advisor (
    advisor_id    STRING,
    advisor_name  STRING,
    branch_code   STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/dim_advisor/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_dim_security (
    security_id    STRING,
    security_name  STRING,
    asset_class    STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/dim_security/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_dim_date (
    trade_date     DATE,
    trade_year     INT,
    trade_month    INT,
    trade_quarter  INT
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/dim_date/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

-- ---- Analytical rollup (BI-ready) ---------------------------------------
CREATE TABLE IF NOT EXISTS advisory_transactions_db.gold_advisor_daily_summary (
    advisor_id         STRING,
    trade_date         DATE,
    total_net_amount   DECIMAL(18,2),
    total_commission   DECIMAL(18,2),
    transaction_count  BIGINT
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/advisor_daily_summary/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');

-- Example consumer query (Athena / QuickSight):
-- SELECT a.advisor_name, s.trade_date, s.total_net_amount
-- FROM advisory_transactions_db.gold_advisor_daily_summary s
-- JOIN advisory_transactions_db.gold_dim_advisor a USING (advisor_id)
-- ORDER BY s.total_net_amount DESC;
