-- Generated by: Transformation Agent (Phase 4b) | zone: GOLD
-- Flat Iceberg: one current row per sku (no star, no rollups).
CREATE TABLE IF NOT EXISTS product_inventory_db.gold_product_inventory (
    sku              STRING,
    product_name     STRING,
    category         STRING,
    warehouse_id     STRING,
    on_hand_qty      INT,
    reserved_qty     INT,
    unit_cost        DECIMAL(18,2),
    list_price       DECIMAL(18,2),
    supplier_id      STRING,
    supplier_name    STRING,
    status           STRING,
    updated_at       TIMESTAMP,
    available_qty    INT,
    inventory_value  DECIMAL(18,2),
    margin_pct       DECIMAL(18,6)
)
LOCATION 's3://data-lake-<account>-us-east-1/gold/product_inventory/'
TBLPROPERTIES (
    'table_type' = 'ICEBERG',
    'format' = 'parquet',
    'write_compression' = 'snappy'
);
