# Generated by: DevOps Agent (/devops-workflow <workload> terraform)
# Provisions one workload's pipeline: zone-scoped KMS, Glue database + jobs,
# Lambdas, Step Functions state machine, EventBridge schedule, SNS alerts, IAM.
# Orchestration = Step Functions + EventBridge Scheduler (NO MWAA -> no ~$350/mo).

locals {
  name = "${var.workload}-${var.environment}"
  tags = merge(var.tags, {
    Project    = "ADOP-Pilot"
    Workload   = var.workload
    Compliance = var.compliance_tag
    ManagedBy  = "Terraform"
  })
}

# ---- Zone-scoped KMS (ADOP `zone-scoped-kms`: one CMK per Bronze/Silver/Gold) ----
resource "aws_kms_key" "zone" {
  for_each                = toset(["bronze", "silver", "gold"])
  description             = "CMK for ${var.workload} ${each.key} zone"
  enable_key_rotation     = true # `kms-rotation` verifier check
  deletion_window_in_days = 7    # pilot minimum: destroyed keys still bill until the window closes
  tags                    = merge(local.tags, { Zone = each.key })
}

resource "aws_kms_alias" "zone" {
  for_each      = aws_kms_key.zone
  name          = "alias/${var.workload}-${each.key}"
  target_key_id = each.value.key_id
}

# ---- Glue Data Catalog database ----
resource "aws_glue_catalog_database" "db" {
  name = "${var.workload}_db"
}

# ---- SNS alert topic ----
resource "aws_sns_topic" "alerts" {
  name = "${var.workload}-alerts"
  tags = local.tags
}

resource "aws_sns_topic_subscription" "email" {
  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# ---- IAM role for Step Functions ----
data "aws_iam_policy_document" "sfn_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["states.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "sfn" {
  name               = "${local.name}-sfn-role"
  assume_role_policy = data.aws_iam_policy_document.sfn_assume.json
  tags               = local.tags
}

# Least-privilege: only the specific Glue jobs, Lambdas, and SNS topic used here.
data "aws_iam_policy_document" "sfn_permissions" {
  statement {
    sid     = "RunGlueJobs"
    actions = ["glue:StartJobRun", "glue:GetJobRun", "glue:GetJobRuns", "glue:BatchStopJobRun"]
    resources = [
      "arn:aws:glue:${var.aws_region}:${var.account_id}:job/${var.workload}_*"
    ]
  }
  statement {
    sid       = "InvokeLambdas"
    actions   = ["lambda:InvokeFunction"]
    resources = [for k in keys(var.lambda_functions) : aws_lambda_function.fn[k].arn]
  }
  statement {
    sid       = "PublishAlerts"
    actions   = ["sns:Publish"]
    resources = [aws_sns_topic.alerts.arn]
  }
}

resource "aws_iam_role_policy" "sfn" {
  name   = "${local.name}-sfn-policy"
  role   = aws_iam_role.sfn.id
  policy = data.aws_iam_policy_document.sfn_permissions.json
}

# ---- Step Functions state machine (definition from the workload artifact) ----
# Every workload's ASL file follows the "<workload>_state_machine.json" convention.
resource "aws_sfn_state_machine" "pipeline" {
  name     = "${var.workload}_pipeline"
  role_arn = aws_iam_role.sfn.arn
  definition = templatefile(
    "${path.module}/../../../../workloads/${var.workload}/orchestration/${var.workload}_state_machine.json",
    { account_id = var.account_id, aws_region = var.aws_region, workload = var.workload }
  )
  tags = local.tags
}

# ---- EventBridge Scheduler role + schedule ----
data "aws_iam_policy_document" "scheduler_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["scheduler.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "scheduler" {
  name               = "${local.name}-scheduler-role"
  assume_role_policy = data.aws_iam_policy_document.scheduler_assume.json
  tags               = local.tags
}

resource "aws_iam_role_policy" "scheduler" {
  name = "${local.name}-scheduler-policy"
  role = aws_iam_role.scheduler.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["states:StartExecution"]
      Resource = [aws_sfn_state_machine.pipeline.arn]
    }]
  })
}

resource "aws_scheduler_schedule" "trigger" {
  name                         = "${var.workload}-${var.schedule_name_suffix}"
  schedule_expression          = var.schedule_expression
  schedule_expression_timezone = "UTC"
  flexible_time_window {
    mode = "OFF"
  }
  target {
    arn      = aws_sfn_state_machine.pipeline.arn
    role_arn = aws_iam_role.scheduler.arn
    input    = jsonencode(var.state_machine_input)
    retry_policy {
      maximum_retry_attempts       = 3
      maximum_event_age_in_seconds = 3600
    }
  }
}
