# Generated by: DevOps Agent. Reusable module -- one instantiation per workload.
# NOTE (adaptation gap): raw resources shown for demo clarity. In a regulated
# enterprise this module's internals map onto the client's approved module
# library (e.g. module "s3_bucket", module "kms_key") -- see docs/ADAPTATION_GAP.md.

variable "workload" {
  type        = string
  description = "Workload name, e.g. advisory_transactions, web_events."
}

variable "environment" {
  type    = string
  default = "dev"
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "account_id" {
  type        = string
  description = "Target AWS account id (sandbox for the pilot)."
}

variable "data_lake_bucket" {
  type        = string
  description = "Base data-lake bucket name (zones + workload scripts are prefixes within it)."
}

variable "alert_email" {
  type        = string
  description = "Email subscribed to this workload's SNS failure/quality-gate topic."
}

variable "compliance_tag" {
  type        = string
  description = "Compliance regime tag, e.g. SOX, GDPR."
}

variable "schedule_expression" {
  type        = string
  description = "EventBridge Scheduler cron/rate expression, e.g. cron(0 7 * * ? *)."
}

variable "schedule_name_suffix" {
  type        = string
  description = "Suffix for the schedule name, e.g. daily, hourly."
  default     = "schedule"
}

variable "state_machine_input" {
  type        = map(string)
  description = "JSON input passed from EventBridge Scheduler into the Step Functions execution."
}

variable "glue_jobs" {
  description = <<-EOT
    Map of Glue job short-name (without the "<workload>_" prefix) -> job spec.
    script_path is relative to the workload directory, e.g. "scripts/extract/ingest_to_bronze.py".
    job_type is "glueetl" (Spark, 2 G.1X workers) or "pythonshell" (0.0625 DPU, cheaper).
  EOT
  type = map(object({
    script_path       = string
    job_type          = string
    default_arguments = optional(map(string), {})
  }))
}

variable "lambda_functions" {
  description = <<-EOT
    Map of Lambda short-name (without the "<workload>_" prefix) -> function spec.
    Deployment package is expected at s3://<data_lake_bucket>/lambda-artifacts/<workload>/<key>.zip
    -- built and uploaded by the CI deploy workflow (see .github/workflows/deploy.yml).
  EOT
  type = map(object({
    handler      = string
    artifact_key = string
    timeout      = optional(number, 60)
    memory_size  = optional(number, 256)
    environment  = optional(map(string), {})
  }))
}

variable "tags" {
  type    = map(string)
  default = {}
}
