-- Generated by: Transformation Agent | zone: SILVER
-- Consent-filtered, deduped, PII-masked. Apache Iceberg on S3 Tables.
-- Encrypted with the Silver-zone KMS CMK (ADOP `zone-scoped-kms` invariant).
-- Only consent_analytics=true events ever reach this table (GDPR).

CREATE TABLE IF NOT EXISTS web_events_db.silver_web_events (
    event_id           STRING,
    user_id            STRING,   -- pseudonymised (hash_token)
    session_id         STRING,
    event_type         STRING,
    event_ts           TIMESTAMP,
    event_hour         TIMESTAMP,
    page_path          STRING,
    traffic_source     STRING,
    ip_address         STRING,   -- masked (last octet zeroed)
    user_email         STRING,   -- masked (u***@domain)
    consent_analytics  BOOLEAN,
    country            STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/web_events/'
TBLPROPERTIES (
    'table_type' = 'ICEBERG',
    'format' = 'parquet',
    'write_compression' = 'snappy'
);

-- Side table for rows that failed critical validity checks (human review).
CREATE TABLE IF NOT EXISTS web_events_db.silver_web_events_quarantine (
    event_id           STRING,
    quarantine_reason  STRING,
    raw_payload        STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/web_events_quarantine/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');
