# Generated by: DevOps Agent (/devops-workflow terraform)
# Root module: instantiates the reusable workload_pipeline module once per
# workload (advisory_transactions = SOX/daily, web_events = GDPR/hourly), plus
# one account-level cost guardrail shared by both.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# ---- advisory_transactions: SOX, daily batch, star schema Gold ----
module "advisory_transactions" {
  source = "./modules/workload_pipeline"

  catalog_owner       = "mcp" # Glue DB via mcp_deploy_infrastructure.py
  kms_owner           = "mcp"
  iam_owner           = "mcp"
  lakeformation_owner = "mcp" # TF fallback: Glue jobs, Lambdas, SFN, Scheduler, SNS
  workload         = "advisory_transactions"
  environment      = var.environment
  aws_region       = var.aws_region
  account_id       = var.account_id
  data_lake_bucket = var.data_lake_bucket
  alert_email      = var.alert_email
  compliance_tag   = "SOX"
  tags             = var.tags

  schedule_expression  = "cron(0 7 * * ? *)" # daily 07:00 UTC, after overnight custodial feed
  schedule_name_suffix = "daily"
  state_machine_input = {
    source_path = "s3://${var.data_lake_bucket}/landing/advisory_transactions/"
    bronze_path = "s3://${var.data_lake_bucket}/bronze/advisory_transactions/"
    silver_path = "s3://${var.data_lake_bucket}/silver/advisory_transactions/"
    gold_path   = "s3://${var.data_lake_bucket}/gold/advisory_transactions/"
  }

  # Mixed compute per config/compute.yaml: Python Shell ingest + quality;
  # Glue ETL (PySpark + Iceberg) for Silver/Gold transforms.
  glue_jobs = {
    ingest_to_bronze = { script_path = "scripts/extract/ingest_to_bronze.py", job_type = "pythonshell" }
    bronze_to_silver = {
      script_path = "scripts/transform/bronze_to_silver.py",
      job_type      = "glueetl",
      default_arguments = {
        "--database"     = "advisory_transactions_db",
        "--silver_table" = "silver_advisory_transactions",
      },
    }
    quality_silver = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "silver", "--data_lake_bucket" = var.data_lake_bucket } }
    silver_to_gold = {
      script_path = "scripts/transform/silver_to_gold.py",
      job_type      = "glueetl",
      default_arguments = {
        "--database" = "advisory_transactions_db",
      },
    }
    quality_gold = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "gold", "--data_lake_bucket" = var.data_lake_bucket } }
  }

  lambda_functions = {
    register_catalog     = { handler = "workloads.advisory_transactions.scripts.load.register_catalog.lambda_handler", artifact_key = "register_catalog" }
    post_deploy_verifier = { handler = "shared.utils.post_deployment_verifier.lambda_handler", artifact_key = "post_deploy_verifier", timeout = 180 }
  }

  # Opt-in sinks (compute.yaml sinks.* / SFN spec enable_*). Default off — no Redshift/OpenSearch/Redis cost.
  enabled_sinks = []
}

# >>> PILOT-DISABLED (advisory_only sandbox deploy). Restore by uncommenting
# this block and the web_events entries in outputs.tf, then re-run
# tools/package_and_sync.py --workload web_events so its Lambda zips exist.
# ---- web_events: GDPR, hourly micro-batch, rollup + erasure index Gold ----
# module "web_events" {
#   source = "./modules/workload_pipeline"
#
#   workload         = "web_events"
#   environment      = var.environment
#   aws_region       = var.aws_region
#   account_id       = var.account_id
#   data_lake_bucket = var.data_lake_bucket
#   alert_email      = var.alert_email
#   compliance_tag   = "GDPR"
#   tags             = var.tags
#
#   schedule_expression  = "cron(5 * * * ? *)" # hourly at :05
#   schedule_name_suffix = "hourly"
#   state_machine_input = {
#     source_path = "s3://${var.data_lake_bucket}/landing/web_events/"
#     bronze_path = "s3://${var.data_lake_bucket}/bronze/web_events/"
#     silver_path = "s3://${var.data_lake_bucket}/silver/web_events/"
#     gold_path   = "s3://${var.data_lake_bucket}/gold/web_events/"
#   }
#
#   glue_jobs = {
#     ingest_to_bronze = { script_path = "scripts/extract/ingest_to_bronze.py", job_type = "glueetl" }
#     bronze_to_silver = { script_path = "scripts/transform/bronze_to_silver.py", job_type = "glueetl" }
#     quality_silver   = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "silver" } }
#     silver_to_gold   = { script_path = "scripts/transform/silver_to_gold.py", job_type = "glueetl" }
#     quality_gold     = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "gold" } }
#   }
#
#   lambda_functions = {
#     register_catalog     = { handler = "workloads.web_events.scripts.load.register_catalog.lambda_handler", artifact_key = "register_catalog" }
#     post_deploy_verifier = { handler = "shared.utils.post_deployment_verifier.lambda_handler", artifact_key = "post_deploy_verifier" }
#   }
# }
# <<< PILOT-DISABLED

# Extension sinks (Redshift / OpenSearch / Redis) are not hardcoded here.
# Enable via compute.yaml `sinks:` + matching state_machine.spec.yaml flags,
# then `python tools/ensure_terraform_module.py --workload {name}`.
# See docs/EXTENDING_TO_NEW_SERVICES.md.

# ---- Cost guardrail: single account-level budget alert (pilot's $25 threshold) ----
resource "aws_budgets_budget" "pilot" {
  name         = "adop-pilot-monthly"
  budget_type  = "COST"
  limit_amount = "25"
  limit_unit   = "USD"
  time_unit    = "MONTHLY"

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 80
    threshold_type             = "PERCENTAGE"
    notification_type          = "ACTUAL"
    subscriber_email_addresses = [var.alert_email]
  }
}
