# Generated by: DevOps Agent (/devops-workflow terraform)
# NOTE: web_events entries are PILOT-DISABLED for the advisory_only sandbox
# deploy (see main.tf). Uncomment them when restoring the second workload.

output "state_machine_arns" {
  value = {
    advisory_transactions = module.advisory_transactions.state_machine_arn
    # web_events            = module.web_events.state_machine_arn
  }
}

output "glue_job_names" {
  value = {
    advisory_transactions = module.advisory_transactions.glue_job_names
    # web_events            = module.web_events.glue_job_names
  }
  description = "Glue job names (5 per workload)."
}

output "lambda_function_arns" {
  value = {
    advisory_transactions = module.advisory_transactions.lambda_function_arns
    # web_events            = module.web_events.lambda_function_arns
  }
  description = "Lambda function ARNs (2 per workload, excluding extension Lambdas)."
}

output "glue_databases" {
  value = {
    advisory_transactions = module.advisory_transactions.glue_database
    # web_events            = module.web_events.glue_database
  }
}

output "kms_key_aliases" {
  value = {
    advisory_transactions = module.advisory_transactions.kms_key_aliases
    # web_events            = module.web_events.kms_key_aliases
  }
}

output "alerts_topic_arns" {
  value = {
    advisory_transactions = module.advisory_transactions.alerts_topic_arn
    # web_events            = module.web_events.alerts_topic_arn
  }
}

# ---- Extension outputs (advisory_transactions only) ----
output "redshift_workgroup_endpoint" {
  value = module.advisory_transactions_redshift.workgroup_endpoint
}

output "opensearch_domain_endpoint" {
  value = module.advisory_transactions_opensearch.domain_endpoint
}

output "redis_endpoint" {
  value = module.advisory_transactions_redis.redis_endpoint
}
