# Generated by: DevOps Agent (/devops-workflow terraform)
# NOTE (adaptation gap): raw resources shown for demo clarity. In a regulated
# enterprise these map onto the client's approved Terraform module library
# (e.g. module "s3_bucket", module "kms_key") -- see docs/ADAPTATION_GAP.md.

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "account_id" {
  type        = string
  description = "Target AWS account id (sandbox for the pilot)."
}

variable "environment" {
  type    = string
  default = "dev"
}

variable "data_lake_bucket" {
  type        = string
  description = "Base data-lake bucket name (zones + workload scripts + lambda artifacts are prefixes within it)."
}

variable "alert_email" {
  type        = string
  description = "Email subscribed to both workloads' SNS alerts and the account budget alert."
}

variable "sandbox_vpc_id" {
  type        = string
  default     = null
  description = "VPC for the Redis and Redshift Serverless extension modules. Null tries the account's default VPC; set explicitly if the account has none (aws ec2 describe-vpcs)."
}

variable "tags" {
  type = map(string)
  default = {
    Project = "ADOP-Pilot"
  }
}
