# AUTO-GENERATED by tools/ensure_terraform_module.py — 2026-09-14
# Workload: customer_orders. Regenerate; do not hand-edit.

module "customer_orders" {
  source = "./modules/workload_pipeline"

  catalog_owner          = "mcp"
  kms_owner              = "mcp"
  iam_owner              = "mcp"
  lakeformation_owner    = "mcp"
  workload               = "customer_orders"
  environment            = var.environment
  aws_region             = var.aws_region
  account_id             = var.account_id
  data_lake_bucket       = var.data_lake_bucket
  alert_email            = var.alert_email
  compliance_tag         = "NONE"
  tags                   = var.tags
  orchestrator           = "mwaa"
  glue_optional_py_files = ["pandas_engine.py", "spark_transforms.py", "local_runner.py"]
  enabled_sinks          = []

  schedule_expression  = "0 7 * * *"
  schedule_name_suffix = "daily"
  state_machine_input = {
    source_path = "s3://${var.data_lake_bucket}/landing/customer_orders/"
    bronze_path = "s3://${var.data_lake_bucket}/bronze/customer_orders/"
    silver_path = "s3://${var.data_lake_bucket}/silver/customer_orders/"
    gold_path   = "s3://${var.data_lake_bucket}/gold/customer_orders/"
  }

  glue_jobs = {
    ingest_to_bronze = { script_path = "scripts/extract/ingest_to_bronze.py", job_type = "pythonshell" }
    bronze_to_silver = {
      script_path = "scripts/transform/bronze_to_silver.py",
      job_type    = "glueetl",
      default_arguments = {
        "--database"     = "customer_orders_db",
        "--silver_table" = "silver_customer_orders",
      },
    }
    quality_silver = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "silver", "--data_lake_bucket" = var.data_lake_bucket } }
    silver_to_gold = {
      script_path = "scripts/transform/silver_to_gold.py",
      job_type    = "glueetl",
      default_arguments = {
        "--database" = "customer_orders_db",
      },
    }
    quality_gold = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "gold", "--data_lake_bucket" = var.data_lake_bucket } }
  }

  lambda_functions = {
    register_catalog     = { handler = "workloads.customer_orders.scripts.load.register_catalog.lambda_handler", artifact_key = "register_catalog" }
    post_deploy_verifier = { handler = "shared.utils.post_deployment_verifier.lambda_handler", artifact_key = "post_deploy_verifier", timeout = 180 }
  }
}
