# AUTO-GENERATED by tools/ensure_terraform_module.py — 2026-09-09
# Workload: supplier_lead_times. Regenerate; do not hand-edit.

module "supplier_lead_times" {
  source = "./modules/workload_pipeline"

  catalog_owner       = "terraform"
  kms_owner           = "terraform"
  iam_owner           = "terraform"
  lakeformation_owner = "terraform"
  workload         = "supplier_lead_times"
  environment      = var.environment
  aws_region       = var.aws_region
  account_id       = var.account_id
  data_lake_bucket = var.data_lake_bucket
  alert_email      = var.alert_email
  compliance_tag   = "NONE"
  tags             = var.tags

  schedule_expression  = "cron(0 6 ? * MON *)"
  schedule_name_suffix = "daily"
  state_machine_input = {
    source_path = "s3://${var.data_lake_bucket}/landing/supplier_lead_times/"
    bronze_path = "s3://${var.data_lake_bucket}/bronze/supplier_lead_times/"
    silver_path = "s3://${var.data_lake_bucket}/silver/supplier_lead_times/"
    gold_path   = "s3://${var.data_lake_bucket}/gold/supplier_lead_times/"
  }

  glue_jobs = {
    ingest_to_bronze = { script_path = "scripts/extract/ingest_to_bronze.py", job_type = "pythonshell" }
    bronze_to_silver = {
      script_path = "scripts/transform/bronze_to_silver.py",
      job_type      = "glueetl",
      default_arguments = {
        "--database"     = "supplier_lead_times_db",
        "--silver_table" = "silver_supplier_lead_times",
      },
    }
    quality_silver = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "silver", "--data_lake_bucket" = var.data_lake_bucket } }
    silver_to_gold = {
      script_path = "scripts/transform/silver_to_gold.py",
      job_type      = "glueetl",
      default_arguments = {
        "--database" = "supplier_lead_times_db",
      },
    }
    quality_gold = { script_path = "scripts/quality/run_quality_checks.py", job_type = "pythonshell", default_arguments = { "--zone" = "gold", "--data_lake_bucket" = var.data_lake_bucket } }
  }

  lambda_functions = {
    register_catalog     = { handler = "workloads.supplier_lead_times.scripts.load.register_catalog.lambda_handler", artifact_key = "register_catalog" }
    post_deploy_verifier = { handler = "shared.utils.post_deployment_verifier.lambda_handler", artifact_key = "post_deploy_verifier", timeout = 180 }
  }
}
