-- Generated by: Transformation Agent | zone: BRONZE
-- Raw, immutable landing table for the hourly clickstream JSONL flush.
-- Partitioned by ingestion_hour. External table over the raw S3 prefix.

CREATE EXTERNAL TABLE IF NOT EXISTS web_events_db.bronze_web_events (
    event_id           STRING,
    user_id            STRING,
    session_id         STRING,
    event_type         STRING,
    event_ts           STRING,
    page_path          STRING,
    traffic_source     STRING,
    ip_address         STRING,
    user_email         STRING,
    consent_analytics  BOOLEAN,
    country            STRING,
    ingestion_ts       STRING
)
PARTITIONED BY (ingestion_hour STRING)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://data-lake-<account>-us-east-1/bronze/web_events/'
TBLPROPERTIES ('classification' = 'json');

-- Bronze is append-only. Never UPDATE/DELETE (ADOP `bronze-immutable` invariant).
-- Right-to-erasure requests are handled at Silver/Gold via the hashed-token
-- erasure index; Bronze retains the immutable raw record per audit policy
-- until the 365-day GDPR retention window expires (lifecycle rule, not a delete).
