-- Generated by: Transformation Agent (Phase 4b) | zone: SILVER
-- Cleaned, typed, deduplicated, PII-masked. Apache Iceberg on S3 Tables.
-- Encrypted with the Silver-zone KMS CMK (ADOP `zone-scoped-kms` invariant).

CREATE TABLE IF NOT EXISTS advisory_transactions_db.silver_advisory_transactions (
    transaction_id    STRING,
    account_id        STRING,
    advisor_id        STRING,
    client_id         STRING,   -- pseudonymised (hash_token)
    client_name       STRING,   -- PII (LF-Tag NAME/HIGH)
    client_email      STRING,   -- masked (j***@domain)
    client_ssn        STRING,   -- masked (***-**-6789)
    security_id       STRING,
    security_name     STRING,
    asset_class       STRING,
    transaction_type  STRING,
    trade_date        DATE,
    settlement_date   DATE,
    quantity          DECIMAL(18,2),
    unit_price        DECIMAL(18,2),
    gross_amount      DECIMAL(18,2),
    commission        DECIMAL(18,2),
    fees              DECIMAL(18,2),
    net_amount        DECIMAL(18,2),
    currency          STRING,
    account_type      STRING,
    advisor_name      STRING,
    branch_code       STRING,
    trade_year        INT,
    trade_month       INT
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/advisory_transactions/'
TBLPROPERTIES (
    'table_type' = 'ICEBERG',
    'format' = 'parquet',
    'write_compression' = 'snappy'
);

-- Side table for rows that failed critical validity checks (SOX human review).
CREATE TABLE IF NOT EXISTS advisory_transactions_db.silver_advisory_transactions_quarantine (
    transaction_id     STRING,
    quarantine_reason  STRING,
    raw_payload        STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/advisory_transactions_quarantine/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');
