-- Generated by: Transformation Agent (Phase 4b) | zone: BRONZE
CREATE EXTERNAL TABLE IF NOT EXISTS product_inventory_db.bronze_product_inventory (
    sku             STRING,
    product_name    STRING,
    category        STRING,
    warehouse_id    STRING,
    on_hand_qty     STRING,
    reserved_qty    STRING,
    unit_cost       STRING,
    list_price      STRING,
    supplier_id     STRING,
    supplier_name   STRING,
    status          STRING,
    updated_at      STRING
)
PARTITIONED BY (ingestion_date STRING)
STORED AS PARQUET
LOCATION 's3://data-lake-<account>-us-east-1/bronze/product_inventory/'
TBLPROPERTIES ('parquet.compression' = 'SNAPPY');

-- Bronze is append-only. Never UPDATE/DELETE (ADOP bronze-immutable).
