-- Generated by: Transformation Agent (Phase 4b) | zone: SILVER
CREATE TABLE IF NOT EXISTS product_inventory_db.silver_product_inventory (
    sku              STRING,
    product_name     STRING,
    category         STRING,
    warehouse_id     STRING,
    on_hand_qty      INT,
    reserved_qty     INT,
    unit_cost        DECIMAL(18,2),
    list_price       DECIMAL(18,2),
    supplier_id      STRING,
    supplier_name    STRING,
    status           STRING,
    updated_at       TIMESTAMP,
    available_qty    INT,
    inventory_value  DECIMAL(18,2),
    margin_pct       DECIMAL(18,6)
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/product_inventory/'
TBLPROPERTIES (
    'table_type' = 'ICEBERG',
    'format' = 'parquet',
    'write_compression' = 'snappy'
);

CREATE TABLE IF NOT EXISTS product_inventory_db.silver_product_inventory_quarantine (
    sku                STRING,
    quarantine_reason  STRING,
    raw_payload        STRING
)
LOCATION 's3://data-lake-<account>-us-east-1/silver/product_inventory_quarantine/'
TBLPROPERTIES ('table_type' = 'ICEBERG', 'format' = 'parquet');
